image: ondrejsika/ci

stages:
  - build
  - test
  - deploy_dev
  - deploy_prod

variables:
  IMAGE: $CI_REGISTRY_IMAGE
  TAG: $CI_COMMIT_REF_SLUG
  COMPOSE_PROJECT_NAME: $CI_JOB_ID

before_script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  stage: build
  variables:
    COMPOSE_FILE: docker-compose.yml:docker-compose-tests.yml
  script:
    - docker-compose build --pull
    - docker-compose push

test:
  stage: test
  variables:
    COMPOSE_FILE: docker-compose.yml:docker-compose-tests.yml
  script:
    - docker-compose pull
    - docker-compose up --no-build tests
  after_script:
    - docker-compose down

.deploy_dev_template: &deploy_dev_template
  stage: deploy_dev
  variables:
    DOCKER_HOST: tcp://$BASE_HOST:2376
    COMPOSE_FILE: docker-compose.yml:docker-compose-traefik.yml
    COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
    HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_HOST

.deploy_dev: &deploy_dev
  <<: *deploy_dev_template
  script:
    - docker-compose pull
    - docker-compose up -d --no-build
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_HOST
    on_stop: stop_deploy_dev

deploy_dev_auto:
  <<: *deploy_dev
  only:
    - master
    - staging

deploy_dev_manual:
  <<: *deploy_dev
  except:
    - master
  when: manual

stop_deploy_dev:
  <<: *deploy_dev_template
  when: manual
  script:
    - docker-compose down --volumes
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop

deploy_prod:
  when: manual
  stage: deploy_prod
  variables:
    DOCKER_HOST: tcp://$BASE_HOST:2376
    COMPOSE_FILE: docker-compose.yml:docker-compose-traefik.yml
    COMPOSE_PROJECT_NAME: $PRODUCTION_HOST
    HOST: $PRODUCTION_HOST
  script:
    - docker-compose pull
    - docker-compose up -d --no-build
  environment:
    name: $PRODUCTION_HOST
    url: https://$PRODUCTION_HOST
